### ISSUE TITLE
Incomprehensible error message when replacement text contains unknown glyphs with "charmap" encoding

### ISSUE THREAD

**Issue by 5780358** [hoehermann/pypdf_strreplace#3]
```Traceback (most recent call last):
  File "test.py", line 140, in <module>
    class PDFOperationTJ(PDFOperation):
  File "test.py", line 141, in PDFOperationTJ
    def __init__(self, operands: list[list[Union[TextStringObject, ByteStringObject, NumberObject]]], context: Context):
TypeError: 'type' object is not subscriptable
```

**Comment by hoehermann** [comment]
Hi @5780358 

Thank you for your message. This repository contains only one python script which is called `pypdf_strreplace.py`. `test.py` is not a file of this project.

Kind Regards  
Hermann

**Comment by 5780358** [comment]
您好，我是胡松，我已经收到您的邮件并会尽快回复。

**Comment by 5780358** [comment]
ok,when i run pypdf_strreplace.py on windows，

```
> python pypdf_strreplace.py --input pdfs/Inkscape.pdf
Traceback (most recent call last):
  File "pypdf_strreplace.py", line 113, in <module>
    class PDFOperationTJ(PDFOperation):
  File "pypdf_strreplace.py", line 114, in PDFOperationTJ
    def __init__(self, operands:list[list[Union[TextStringObject,ByteStringObject,NumberObject]]], context:Context):
TypeError: 'type' object is not subscriptable
```

and run ubuntu

```
$ python3 pypdf_strreplace.py --input pdfs/Inkscape.pdf
Traceback (most recent call last):
  File "pypdf_strreplace.py", line 113, in <module>
    class PDFOperationTJ(PDFOperation):
  File "pypdf_strreplace.py", line 114, in PDFOperationTJ
    def __init__(self, operands:list[list[Union[TextStringObject,ByteStringObject,NumberObject]]], context:Context):
TypeError: 'type' object is not subscriptable
```

**Comment by hoehermann** [comment]
Interesting. It looks like https://docs.python.org/3/library/typing.html is not understood by your python interpreter. Which version of python are you using? As far as I know, at least 3.7 is needed. I only tried version 3.10. I cannot tell whether anything older might work.

**Comment by 5780358** [comment]
The program can be executed in Python versions above 10. Now there is an error when replacing Chinese characters.

```
C:\Users\test\Downloads\pypdf_strreplace-master>python pypdf_strreplace.py --input 123.pdf --search "你好朋友" --replace "再见伙伴" --output out.pdf
Traceback (most recent call last):
  File "C:\Users\test\Downloads\pypdf_strreplace-master\pypdf_strreplace.py", line 276, in <module>
    total_replacements += replace_text(contents, charmaps, args.search, args.replace)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\Downloads\pypdf_strreplace-master\pypdf_strreplace.py", line 237, in replace_text
    operations = replace_operations(operations, start, end, replacement, charmaps)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\Downloads\pypdf_strreplace-master\pypdf_strreplace.py", line 206, in replace_operations
    operation.replace_text(replacement, charmaps, start.operand, end_operand)
  File "C:\Users\test\Downloads\pypdf_strreplace-master\pypdf_strreplace.py", line 156, in replace_text
    self.operands[0] = charmaps[self.context.font].encode(text, self.operands[0])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\Downloads\pypdf_strreplace-master\pypdf_strreplace.py", line 41, in encode
    return ByteStringObject(text.translate(str.maketrans(map)).encode('ascii')) # encoding with ascii is a wild guess
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```
[123.pdf](https://github.com/user-attachments/files/16230064/123.pdf)

**Comment by hoehermann** [comment]
Thank you for your message. The sample document you provided was very helpful in understanding the issue.

This tool is not good enough for your mission. This tool can only eliminate or move characters in the document. This can work:

    python pypdf_strreplace.py --input pdfs/123.pdf --search "你好朋友" --replace "砺进啥砥奋" --output out.pdf

However, this can not work:

    python pypdf_strreplace.py --input pdfs/123.pdf --search "你好朋友" --replace "再见 伙伴" --output out.pdf

再 does not exist in the input document. Unfortunately, this tool cannot "inject" new characters. I am sorry.

I added an error message which makes the problem more clear. Thank you for your contribution.

**Comment by 5780358** [comment]
您好，我是胡松，我已经收到您的邮件并会尽快回复。
