### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte

### ISSUE THREAD

**Issue by ProgrammerKrot** [hoehermann/pypdf_strreplace#7]
Hi! Ive tried to use your code to automatize text replacement in my document and it is working fine for some parts! However, I can't understand the issue with some specific pages...
```
# These fonts are referenced on page 1: /SSYEVS+FrutigerLTCom-Light, /SSYEVS+Universal-NewswithCommPi, /SSYEVS+MeliorCom, /SSYEVS+MeliorCom-Bold, /SSYEVS+FrutigerLTCom-Light
Traceback (most recent call last):
  File "/home/werterwork/PycharmProjects/PDFTonyProject1/pypdf_strreplace/pypdf_strreplace.py", line 378, in <module>
    total_replacements += replace_text(contents, args.search, args.replace, args.delete, gui_treeList)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werterwork/PycharmProjects/PDFTonyProject1/pypdf_strreplace/pypdf_strreplace.py", line 292, in replace_text
    operations = [PDFOperation.from_tuple(operands, operator, context) for operands, operator in content.operations]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werterwork/PycharmProjects/PDFTonyProject1/pypdf_strreplace/pypdf_strreplace.py", line 92, in from_tuple
    return globals()[classname](operands, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werterwork/PycharmProjects/PDFTonyProject1/pypdf_strreplace/pypdf_strreplace.py", line 130, in __init__
    self._infer_plain_text()
  File "/home/werterwork/PycharmProjects/PDFTonyProject1/pypdf_strreplace/pypdf_strreplace.py", line 144, in _infer_plain_text
    operand.plain_text = self.context.charmaps[self.context.font].decode(operand)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werterwork/PycharmProjects/PDFTonyProject1/pypdf_strreplace/pypdf_strreplace.py", line 44, in decode
    return "".join(text.get_original_bytes().decode(encoding).translate(str.maketrans(self.map)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
```
Is there any way to fix it? I am newbie in pdf, so I apologize for any inconvenience that I could cause.

**Comment by ProgrammerKrot** [comment]
Manually changing encoding from utf-8 in 44 line "pypdf_strreplace.py" to windows-1254 helped a lot... Thank you for such a great tool!

**Comment by hoehermann** [comment]
Thank you for your report. Glad you found a workaround. Can you send me the file? Maybe I can add a switch so future users do not need to modify the script.

PS: With this project, I learned more about PDF than I ever wanted to know and I have only scratched the surface. It certainly is an… interesting format.

**Comment by ProgrammerKrot** [comment]
Hello! Yes, I can! Do you mind if I send it to the email on your GitHub page? It's a bit private...
I totally agree with you... PDFs can sometimes be such a mystery...

**Comment by hoehermann** [comment]
Yes, certainly. Thank you.
